moov/config/routes.rb
Rails.application.routes.draw do
  resources :subgroups, has_one: :interest

  resources :nonprofits, has_one: :interest

  resources :events, has_one: :interest

  resources :volunteers, has_one: :interest

  # resources :interests

  get 'static_pages/home'
  get 'static_pages/help'
end

moov/app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
  has_one :interest, as: :interested, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  # TODO: nested form
  # validates :interest, presence: true
end

moov/app/controllers/subgroups_controller.rb
class SubgroupsController < ApplicationController
  before_action :set_subgroup, only: [:show, :edit, :update, :destroy]

  # GET /subgroups
  # GET /subgroups.json
  def index
    @subgroups = Subgroup.all
  end

  # GET /subgroups/1
  # GET /subgroups/1.json
  def show
  end

  # GET /subgroups/new
  def new
    @subgroup = Subgroup.new
  end

  # GET /subgroups/1/edit
  def edit
  end

  # POST /subgroups
  # POST /subgroups.json
  def create
    @subgroup = Subgroup.new(subgroup_params)

    respond_to do |format|
      if @subgroup.save
        format.html { redirect_to @subgroup, notice: 'Subgroup was successfully created.' }
        format.json { render :show, status: :created, location: @subgroup }
      else
        format.html { render :new }
        format.json { render json: @subgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subgroups/1
  # PATCH/PUT /subgroups/1.json
  def update
    respond_to do |format|
      if @subgroup.update(subgroup_params)
        format.html { redirect_to @subgroup, notice: 'Subgroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @subgroup }
      else
        format.html { render :edit }
        format.json { render json: @subgroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subgroups/1
  # DELETE /subgroups/1.json
  def destroy
    @subgroup.destroy
    respond_to do |format|
      format.html { redirect_to subgroups_url, notice: 'Subgroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subgroup
      @subgroup = Subgroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subgroup_params
      params.require(:subgroup).permit(:name)
    end
end

moov/app/helpers/subgroups_helper.rb
module SubgroupsHelper
end

moov/app/views/subgroups/_form.html.erb
<%= form_for(@subgroup) do |f| %>
  <% if @subgroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subgroup.errors.count, "error") %> prohibited this subgroup from being saved:</h2>

      <ul>
      <% @subgroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

moov/app/views/subgroups/edit.html.erb
<h1>Editing subgroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @subgroup %> |
<%= link_to 'Back', subgroups_path %>

moov/app/views/subgroups/index.html.erb
<h1>Listing subgroups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subgroups.each do |subgroup| %>
      <tr>
        <td><%= subgroup.name %></td>
        <td><%= link_to 'Show', subgroup %></td>
        <td><%= link_to 'Edit', edit_subgroup_path(subgroup) %></td>
        <td><%= link_to 'Destroy', subgroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subgroup', new_subgroup_path %>

moov/app/views/subgroups/new.html.erb
<h1>New subgroup</h1>

<%= render 'form' %>

<%= link_to 'Back', subgroups_path %>

moov/app/views/subgroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subgroup.name %>
</p>

<%= link_to 'Edit', edit_subgroup_path(@subgroup) %> |
<%= link_to 'Back', subgroups_path %>