moov/config/routes.rb
Rails.application.routes.draw do
  resources :subgroups, has_one: :interest

  resources :nonprofits, has_one: :interest

  resources :events, has_one: :interest

  resources :volunteers, has_one: :interest

  # resources :interests

  get 'static_pages/home'
  get 'static_pages/help'
end

moov/app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  has_one :interest, as: :interested, dependent: :destroy
  has_one :leader,  class_name: 'Volunteer'

  has_many :events, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  # TODO: nested form
  # validates :interest, presence: true
end

moov/app/controllers/nonprofits_controller.rb
class NonprofitsController < ApplicationController
  before_action :set_nonprofit, only: [:show, :edit, :update, :destroy]

  # GET /nonprofits
  # GET /nonprofits.json
  def index
    @nonprofits = Nonprofit.all
  end

  # GET /nonprofits/1
  # GET /nonprofits/1.json
  def show
  end

  # GET /nonprofits/new
  def new
    @nonprofit = Nonprofit.new
  end

  # GET /nonprofits/1/edit
  def edit
  end

  # POST /nonprofits
  # POST /nonprofits.json
  def create
    @nonprofit = Nonprofit.new(nonprofit_params)

    respond_to do |format|
      if @nonprofit.save
        format.html { redirect_to @nonprofit, notice: 'Nonprofit was successfully created.' }
        format.json { render :show, status: :created, location: @nonprofit }
      else
        format.html { render :new }
        format.json { render json: @nonprofit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nonprofits/1
  # PATCH/PUT /nonprofits/1.json
  def update
    respond_to do |format|
      if @nonprofit.update(nonprofit_params)
        format.html { redirect_to @nonprofit, notice: 'Nonprofit was successfully updated.' }
        format.json { render :show, status: :ok, location: @nonprofit }
      else
        format.html { render :edit }
        format.json { render json: @nonprofit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nonprofits/1
  # DELETE /nonprofits/1.json
  def destroy
    @nonprofit.destroy
    respond_to do |format|
      format.html { redirect_to nonprofits_url, notice: 'Nonprofit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nonprofit
      @nonprofit = Nonprofit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nonprofit_params
      params.require(:nonprofit).permit(:name)
    end
end

moov/app/helpers/nonprofits_helper.rb
module NonprofitsHelper
end

moov/app/views/nonprofits/_form.html.erb
<%= form_for(@nonprofit) do |f| %>
  <% if @nonprofit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nonprofit.errors.count, "error") %> prohibited this nonprofit from being saved:</h2>

      <ul>
      <% @nonprofit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

moov/app/views/nonprofits/edit.html.erb
<h1>Editing nonprofit</h1>

<%= render 'form' %>

<%= link_to 'Show', @nonprofit %> |
<%= link_to 'Back', nonprofits_path %>

moov/app/views/nonprofits/index.html.erb
<h1>Listing nonprofits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nonprofits.each do |nonprofit| %>
      <tr>
        <td><%= nonprofit.name %></td>
        <td><%= link_to 'Show', nonprofit %></td>
        <td><%= link_to 'Edit', edit_nonprofit_path(nonprofit) %></td>
        <td><%= link_to 'Destroy', nonprofit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nonprofit', new_nonprofit_path %>

moov/app/views/nonprofits/new.html.erb
<h1>New nonprofit</h1>

<%= render 'form' %>

<%= link_to 'Back', nonprofits_path %>

moov/app/views/nonprofits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nonprofit.name %>
</p>

<%= link_to 'Edit', edit_nonprofit_path(@nonprofit) %> |
<%= link_to 'Back', nonprofits_path %>