moov/config/routes.rb
Rails.application.routes.draw do
  resources :subgroups, has_one: :interest

  resources :nonprofits, has_one: :interest

  resources :events, has_one: :interest

  resources :volunteers, has_one: :interest

  # resources :interests

  get 'static_pages/home'
  get 'static_pages/help'
end

moov/app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_one :interest, as: :interested, dependent: :destroy

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, confirmation: true, uniqueness: true,
    format: { with: VALID_EMAIL_REGEX }
  validates :bday, presence: true
  # validates :approved?
  # validates :leader?
  # validates :admin?

  # TODO: nested form
  # validates :interest, presence: true
end

moov/app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]

  # GET /volunteers
  # GET /volunteers.json
  def index
    @volunteers = Volunteer.all
  end

  # GET /volunteers/1
  # GET /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers
  # POST /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)

    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully created.' }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1
  # PATCH/PUT /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: 'Volunteer was successfully updated.' }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1
  # DELETE /volunteers/1.json
  def destroy
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to volunteers_url, notice: 'Volunteer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def volunteer_params
      params.require(:volunteer).permit(:name, :bday, :email)# ,:approved?, :leader?, :admin?, :email)
    end
end

moov/app/helpers/volunteers_helper.rb
module VolunteersHelper
end

moov/app/views/volunteers/_form.html.erb
<%= form_for(@volunteer) do |f| %>
  <% if @volunteer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited this volunteer from being saved:</h2>

      <ul>
      <% @volunteer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bday %><br>
    <%= f.date_select :bday, { start_year: Date.today.year, end_year: Date.today.year - 100, order: [:month, :day, :year] } %>
  </div>
  <!--
  <div class="field">
    <#%= f.label :approved? %><br>
    <#%= f.check_box :approved? %>
  </div>
  <div class="field">
    <#%= f.label :leader? %><br>
    <#%= f.check_box :leader? %>
  </div>
  <div class="field">
    <#%= f.label :admin? %><br>
    <#%= f.check_box :admin? %>
  </div>
  -->
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

moov/app/views/volunteers/edit.html.erb
<h1>Editing volunteer</h1>

<%= render 'form' %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

moov/app/views/volunteers/index.html.erb
<h1>Listing volunteers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bday</th>
      <th>Approved?</th>
      <th>Leader?</th>
      <th>Admin?</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteers.each do |volunteer| %>
      <tr>
        <td><%= volunteer.name %></td>
        <td><%= volunteer.bday %></td>
        <td><%= volunteer.approved? %></td>
        <td><%= volunteer.leader? %></td>
        <td><%= volunteer.admin? %></td>
        <td><%= volunteer.email %></td>
        <td><%= link_to 'Show', volunteer %></td>
        <td><%= link_to 'Edit', edit_volunteer_path(volunteer) %></td>
        <td><%= link_to 'Destroy', volunteer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volunteer', new_volunteer_path %>

moov/app/views/volunteers/new.html.erb
<h1>New volunteer</h1>

<%= render 'form' %>

<%= link_to 'Back', volunteers_path %>

moov/app/views/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @volunteer.name %>
</p>

<p>
  <strong>Bday:</strong>
  <%= @volunteer.bday %>
</p>

<p>
  <strong>Approved?:</strong>
  <%= @volunteer.approved? %>
</p>

<p>
  <strong>Leader?:</strong>
  <%= @volunteer.leader? %>
</p>

<p>
  <strong>Admin?:</strong>
  <%= @volunteer.admin? %>
</p>

<p>
  <strong>Email:</strong>
  <%= @volunteer.email %>
</p>

<%= link_to 'Edit', edit_volunteer_path(@volunteer) %> |
<%= link_to 'Back', volunteers_path %>